version: "3.3"

networks:
  morgen:

services:
  orderer.morgen.net:
    container_name: orderer.morgen.net
    image: hyperledger/fabric-orderer:1.4.4
    environment:
      - ORDERER_HOME=/tmp/hyperledger/orderer
      - ORDERER_HOST=orderer.morgen.net
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/orderer.morgen.net/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/orderer.morgen.net/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/orderer.morgen.net/orderer/tls-msp/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/orderer.morgen.net/orderer/tls-msp/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/orderer.morgen.net/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
    volumes:
      - ./ca-orderer.morgen.net/orderer:/tmp/hyperledger/orderer.morgen.net/orderer/
      # if you want persistent data
      - ./ca-orderer.morgen.net/orderer/production:/var/hyperledger/production
    networks:
      - morgen
    ports:
      - 7050:7050

  peer0.mars.morgen.net:
    container_name: peer0.mars.morgen.net
    image: hyperledger/fabric-peer:1.4.4
    environment:
      - CORE_PEER_ID=peer0.mars.morgen.net
      - CORE_PEER_ADDRESS=peer0.mars.morgen.net:7051
      - CORE_PEER_LOCALMSPID=marsMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/mars.morgen.net/peer0/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e016_morgen
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/mars.morgen.net/peer0/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/mars.morgen.net/peer0/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/mars.morgen.net/peer0/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mars.morgen.net:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/mars.morgen.net/peer0
    volumes:
      - /var/run:/host/var/run
      - ./ca-mars.morgen.net/peers/peer0:/tmp/hyperledger/mars.morgen.net/peer0
      # if you want persistent data
      - ./ca-mars.morgen.net/peers/peer0/production:/var/hyperledger/production
    networks:
      - morgen
    depends_on:
      - orderer.morgen.net
    ports:
      - 7051:7051


  peer1.mars.morgen.net:
    container_name: peer1.mars.morgen.net
    image: hyperledger/fabric-peer:1.4.4
    environment:
      - CORE_PEER_ID=peer1.mars.morgen.net
      - CORE_PEER_ADDRESS=peer1.mars.morgen.net:7051
      - CORE_PEER_LOCALMSPID=marsMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/mars.morgen.net/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e016_morgen
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/mars.morgen.net/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/mars.morgen.net/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/mars.morgen.net/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mars.morgen.net:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/mars.morgen.net/peer1
    volumes:
      - /var/run:/host/var/run
      - ./ca-mars.morgen.net/peers/peer1:/tmp/hyperledger/mars.morgen.net/peer1
      # if you want persistent data
      - ./ca-mars.morgen.net/peers/peer1/production:/var/hyperledger/production
    networks:
      - morgen
    depends_on:
      - orderer.morgen.net
    ports:
      - 8051:7051
  
  cli-mars.morgen.net:
    container_name: cli-mars.morgen.net
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli-mars.morgen.net
      - CORE_PEER_ADDRESS=peer0.mars.morgen.net:7051
      - CORE_PEER_LOCALMSPID=marsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/mars.morgen.net/peers/peer0/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/mars.morgen.net/admin/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/mars.morgen.net
    command: sh
    volumes:
      - ./ca-mars.morgen.net/peers/:/tmp/hyperledger/mars.morgen.net/peers
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      - ./ca-mars.morgen.net/admin:/tmp/hyperledger/mars.morgen.net/admin
    networks:
      - morgen