version: '2'

networks:
  universe:

services:
  solo.orderer.universe.at:
    image: hyperledger/fabric-orderer:1.4.4
    container_name: solo.orderer.universe.at
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    volumes:
      - ./config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/orderer.universe.at/orderers/solo.orderer.universe.at/msp:/var/hyperledger/orderer/msp
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - universe

  peer0.mars.universe.at:
    container_name: peer0.mars.universe.at
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID= peer0.mars.universe.at
      - CORE_PEER_ADDRESS= peer0.mars.universe.at:7051
      - CORE_PEER_LOCALMSPID=MarsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT= peer0.mars.universe.at:7051
    volumes:
      - ./crypto-config/peerOrganizations/mars.universe.at/peers/peer0.mars.universe.at/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/mars.universe.at/users:/etc/hyperledger/msp/users
      - ./config/channel.tx:/etc/hyperledger/configtx/channel.tx
      
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - solo.orderer.universe.at
    networks:
      - universe

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.mars.universe.at:7051
      - CORE_PEER_LOCALMSPID=MarsMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mars.universe.at/users/Admin@mars.universe.at/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/
    networks:
        - universe
    depends_on:
      - solo.orderer.universe.at
      - peer0.mars.universe.at